package almacen;
// Generated 14/12/2010 06:47:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ingreso generated by hbm2java
 */
public class Ingreso  implements java.io.Serializable {


     private Integer idIngreso;
     private Producto producto;
     private Integer cantidad;
     private Date fecha;
     private String personal;

    public Ingreso() {
    }

    public Ingreso(Producto producto, Integer cantidad, Date fecha, String personal) {
       this.producto = producto;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.personal = personal;
    }
   
    public Integer getIdIngreso() {
        return this.idIngreso;
    }
    
    public void setIdIngreso(Integer idIngreso) {
        this.idIngreso = idIngreso;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(String personal) {
        this.personal = personal;
    }




}


