package almacen;
// Generated 14/12/2010 06:47:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String codProducto;
     private String presentacion;
     private Integer cantidad;
     private Double costo;
     private Double precio;
     private Date fecha;
     private Set salidas = new HashSet(0);
     private Set ingresos = new HashSet(0);

    public Producto() {
    }

    public Producto(String codProducto, String presentacion, Integer cantidad, Double costo, Double precio, Date fecha, Set salidas, Set ingresos) {
       this.codProducto = codProducto;
       this.presentacion = presentacion;
       this.cantidad = cantidad;
       this.costo = costo;
       this.precio = precio;
       this.fecha = fecha;
       this.salidas = salidas;
       this.ingresos = ingresos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodProducto() {
        return this.codProducto;
    }
    
    public void setCodProducto(String codProducto) {
        this.codProducto = codProducto;
    }
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }
    public Set getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set ingresos) {
        this.ingresos = ingresos;
    }




}


