package almacen;
// Generated 14/12/2010 06:47:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private Integer idSalida;
     private Producto producto;
     private Integer cantidad;
     private Date fecha;
     private String personal;

    public Salida() {
    }

    public Salida(Producto producto, Integer cantidad, Date fecha, String personal) {
       this.producto = producto;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.personal = personal;
    }
   
    public Integer getIdSalida() {
        return this.idSalida;
    }
    
    public void setIdSalida(Integer idSalida) {
        this.idSalida = idSalida;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(String personal) {
        this.personal = personal;
    }




}


